services:
  samba:
    image: dockurr/samba
    container_name: samba
    environment:
      USER: "samba"
      PASS: "secret"
    ports:
      - 445:445
    volumes:
      - /home/Samba:/storage
      - /home/Samba/smb.conf:/etc/samba/smb.conf
